"""Pilot 2 — SELF vs OTHER attribution of a single behavioral trajectory.

A Loula-Experiment-1 analogue: one anonymous 50-flip H/T sequence is shown to
a judge and the judge must decide whether it was generated by the same
underlying model as itself (SELF) or by a different model (OTHER).

Reuses the 60 source trajectories generated by the pilot-1 dynamic run.
Uses plain-text one-word responses (SELF or OTHER) rather than structured JSON.
"""

import os, random, time, uuid
from dataclasses import asdict, dataclass, field
from typing import Dict, List, Optional, Tuple

from openai import OpenAI

from . import config as C
from .api import (APIResult, CostAccountant, call_model, parse_self_other,
                  BudgetExceeded)
from .state import RunPaths, read_json, write_json


@dataclass
class SelfOtherTrial:
    trial_id: str
    judge_label: str
    architecture: str
    label: str                # "SELF" | "OTHER"
    source_model_label: str   # actual source model of the shown trajectory
    source_trajectory_id: str
    display_sequence: str
    trial_position: int       # 0-based position within the (judge, arch) block after shuffle
    construction_seed: int


@dataclass
class SelfOtherJudgmentRecord:
    trial_id: str
    judge_label: str
    architecture: str
    correct_answer: str       # SELF | OTHER
    source_model_label: str
    source_trajectory_id: str
    sequence_display: str
    trial_position: int
    construction_seed: int
    prompt_text: str
    prompt_hash: str
    request_id: str
    requested_model: str
    served_model: str
    provider: str
    raw_completion: str
    parsed_judgment: str      # SELF | OTHER | ""
    valid: bool
    correct: Optional[bool]   # None if abandoned
    attempts: int             # number of attempts made
    attempt_records: List[Dict] = field(default_factory=list)
    trial_status: str = "ok"  # "ok" | "abandoned"
    total_cost_usd: float = 0.0
    prompt_tokens: int = 0
    completion_tokens: int = 0
    reasoning_tokens: int = 0
    finish_reason: str = ""
    latency_ms: int = 0
    error_message: str = ""
    call_utc: str = ""
    response_mode: str = "chat"


# --- source-trajectory loading --------------------------------------------

def load_source_trajectories(source_run_root: str) -> Dict[Tuple[str, str], List[Tuple[str, str, str]]]:
    """Return dict[(arch, model_label)] -> list of (model_label, traj_id, sequence).

    Reads the on-disk trajectory records from a completed pilot-1 run.
    """
    out: Dict[Tuple[str, str], List[Tuple[str, str, str]]] = {}
    for arch in C.ARCHITECTURES:
        base = os.path.join(source_run_root, "source", arch)
        for m in C.MODEL_LABELS:
            key = (arch, m)
            out[key] = []
            model_dir = os.path.join(base, m)
            if not os.path.isdir(model_dir):
                continue
            for fn in sorted(os.listdir(model_dir)):
                if not fn.endswith(".json") or ".steps." in fn:
                    continue
                rec = read_json(os.path.join(model_dir, fn))
                if rec and rec.get("valid"):
                    out[key].append((m, rec["trajectory_id"], rec["parsed_sequence"]))
    # sanity: sort within each list for deterministic order
    for k in out:
        out[k].sort(key=lambda x: x[1])
    return out


# --- trial construction ---------------------------------------------------

def _debunch_labels(trials: List[SelfOtherTrial], rng: random.Random,
                    max_run: int = 3, max_iter: int = 200) -> List[SelfOtherTrial]:
    """Reshuffle to avoid runs of more than max_run identical labels."""
    def offense(seq):
        n = 0
        for i in range(max_run, len(seq)):
            if all(seq[j].label == seq[i].label for j in range(i - max_run, i + 1)):
                n += 1
        return n
    best = list(trials); best_off = offense(best)
    for _ in range(max_iter):
        if best_off == 0:
            break
        cand = list(best)
        i, j = rng.sample(range(len(cand)), 2)
        cand[i], cand[j] = cand[j], cand[i]
        o = offense(cand)
        if o < best_off:
            best, best_off = cand, o
    return best


def build_self_other_trials(source_trajectories: Dict[Tuple[str, str], List[Tuple[str, str, str]]],
                            construction_seed: int = C.SELF_OTHER_CONSTRUCTION_SEED) -> List[SelfOtherTrial]:
    """Build 120 SELF/OTHER trials.

    Per (judge, architecture) block:
      - 10 SELF trials: use ALL 10 of the judge's own trajectories exactly once
      - 10 OTHER trials: 5 from each non-self model (sampled deterministically)
    """
    trials: List[SelfOtherTrial] = []
    for judge in C.MODEL_LABELS:
        others = [m for m in C.MODEL_LABELS if m != judge]
        assert len(others) == 2
        for arch in C.ARCHITECTURES:
            block_seed = construction_seed + hash((judge, arch, "self_other")) & 0xffffff
            rng = random.Random(block_seed)

            # SELF: all 10 own trajectories, one trial each
            self_pool = source_trajectories[(arch, judge)]
            assert len(self_pool) >= C.SELF_OTHER_TRIALS_PER_LABEL, \
                f"insufficient SELF trajectories for {judge}/{arch}: {len(self_pool)}"
            self_selected = list(self_pool[:C.SELF_OTHER_TRIALS_PER_LABEL])

            # OTHER: 5 from each non-self model
            other_selected = []
            for other_label in others:
                other_pool = source_trajectories[(arch, other_label)]
                assert len(other_pool) >= C.SELF_OTHER_OTHER_FROM_EACH_NON_SELF, \
                    f"insufficient OTHER trajectories for {other_label}/{arch}: {len(other_pool)}"
                # deterministic sample without replacement of the required count
                idx = rng.sample(range(len(other_pool)), C.SELF_OTHER_OTHER_FROM_EACH_NON_SELF)
                for i in idx:
                    other_selected.append(other_pool[i])

            block = []
            for (m_label, tid, seq) in self_selected:
                block.append(SelfOtherTrial(
                    trial_id=str(uuid.uuid4()), judge_label=judge, architecture=arch,
                    label="SELF", source_model_label=m_label,
                    source_trajectory_id=tid, display_sequence=seq,
                    trial_position=-1, construction_seed=block_seed))
            for (m_label, tid, seq) in other_selected:
                block.append(SelfOtherTrial(
                    trial_id=str(uuid.uuid4()), judge_label=judge, architecture=arch,
                    label="OTHER", source_model_label=m_label,
                    source_trajectory_id=tid, display_sequence=seq,
                    trial_position=-1, construction_seed=block_seed))
            rng.shuffle(block)
            block = _debunch_labels(block, rng, max_run=3)
            for pos, t in enumerate(block):
                # dataclasses are frozen? No - regular dataclass. Just set.
                t.trial_position = pos
                trials.append(t)
    return trials


# --- judgment call --------------------------------------------------------

def judgment_prompt(seq: str) -> str:
    return C.SELF_OTHER_PROMPT_TEMPLATE.format(sequence=seq)


def judge_one_trial(client: OpenAI, accountant: CostAccountant,
                    trial: SelfOtherTrial, judge_slug: str) -> SelfOtherJudgmentRecord:
    prompt = judgment_prompt(trial.display_sequence)
    attempts_meta = []
    parsed = None
    total_cost = 0.0
    last_res: Optional[APIResult] = None
    attempts = 0
    for attempt in range(1, C.SELF_OTHER_MAX_JUDGMENT_ATTEMPTS + 1):
        res = call_model(client, accountant,
                         kind="judgment_self_other", slug=judge_slug,
                         prompt_text=prompt,
                         max_tokens=C.SELF_OTHER_MAX_TOKENS,
                         response_format=None)   # plain-text: no JSON schema
        total_cost += res.cost_usd
        last_res = res
        attempts = attempt
        parsed = parse_self_other(res.response_text)
        attempts_meta.append({
            "attempt_no": attempt,
            "raw_completion": res.response_text,
            "parsed": parsed,
            "served_model": res.served_model, "provider": res.provider,
            "prompt_tokens": res.prompt_tokens,
            "completion_tokens": res.completion_tokens,
            "reasoning_tokens": res.reasoning_tokens,
            "finish_reason": res.finish_reason,
            "cost_usd": res.cost_usd, "latency_ms": res.latency_ms,
            "error_message": res.error_message,
            "call_utc": res.call_utc, "request_id": res.request_id,
        })
        if parsed is not None:
            break
    correct = None
    trial_status = "ok"
    if parsed is None:
        trial_status = "abandoned"
    else:
        correct = (parsed == trial.label)
    return SelfOtherJudgmentRecord(
        trial_id=trial.trial_id, judge_label=trial.judge_label,
        architecture=trial.architecture, correct_answer=trial.label,
        source_model_label=trial.source_model_label,
        source_trajectory_id=trial.source_trajectory_id,
        sequence_display=trial.display_sequence,
        trial_position=trial.trial_position,
        construction_seed=trial.construction_seed,
        prompt_text=prompt, prompt_hash=last_res.prompt_hash if last_res else "",
        request_id=last_res.request_id if last_res else "",
        requested_model=judge_slug,
        served_model=last_res.served_model if last_res else "",
        provider=last_res.provider if last_res else "",
        raw_completion=last_res.response_text if last_res else "",
        parsed_judgment=parsed or "",
        valid=parsed is not None,
        correct=correct,
        attempts=attempts,
        attempt_records=attempts_meta,
        trial_status=trial_status,
        total_cost_usd=total_cost,
        prompt_tokens=last_res.prompt_tokens if last_res else 0,
        completion_tokens=last_res.completion_tokens if last_res else 0,
        reasoning_tokens=last_res.reasoning_tokens if last_res else 0,
        finish_reason=last_res.finish_reason if last_res else "",
        latency_ms=last_res.latency_ms if last_res else 0,
        error_message=last_res.error_message if last_res else "",
        call_utc=last_res.call_utc if last_res else "",
        response_mode="chat",
    )
